# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  name: default
  
variables:
  rgname: "yamlrg"
  loc: "eastus"

steps:
- task: AzurePowerShell@5
  displayName: AZ Powershell yaml
  inputs:
    azureSubscription: 'azure connection1'
    ScriptType: 'InlineScript'
    Inline: |
     new-azresourcegroup -name $rgname -location $loc
